### ISSUE TITLE
Feedback Técnico

### ISSUE THREAD

**Issue by RuthSalvador** [Grecia2727/lim-2018-05-bc-core-am-socialnetwork#27]
# Recomendaciones de mejora 

### Estructura de carpetas:
Te sugiero que puedan tener un orden de archivos, crear carpetas `js` donde estén sus archivos javascript, lo mismo para `css`, etc. Tienen 2 carpetas de imágenes, puedes optar por subirlas a la nube y linkearlas.

### Git:
Es recomendable que "comitées" por funcionalidades, pueden ser descriptivos o anexados a un `issue`, evita usar: imagenes mas img, demo4 finales, demo4 finales2, cambio final, Grabando cambios, etc

### Github:
Bien! llegaste al nivel solicitado, te invito a que averigües más formas de uso.

### Javascript:
- Se considera una buena práctica utilizar los operadores de igualdad de tipo seguro `===` y `!==` en lugar de sus contrapartes regulares `==` y `!=`.
https://github.com/Grecia2727/lim-2018-05-bc-core-am-socialnetwork/blob/c8595fa93dd09be1edb6ac79aabba068ac6a57c7/src/firebase.js#L250
- El proyecto debe estar en `ES6`
https://github.com/Grecia2727/lim-2018-05-bc-core-am-socialnetwork/blob/c8595fa93dd09be1edb6ac79aabba068ac6a57c7/src/social_network.js#L13-L21
- Tus variables deben ser descriptivas...
https://github.com/Grecia2727/lim-2018-05-bc-core-am-socialnetwork/blob/c8595fa93dd09be1edb6ac79aabba068ac6a57c7/src/social_network.js#L6-L9
- Como sugerencia, al ingresar directamente al muro, podría validarme que no estoy logueado y por lo tanto redireccionarme al index; pueden implementarlo.
- Recuerda lo que conversamos sobre los usuarios ingresados con Google, mejoren la publicación de post, sobre todo si van a usar este proyecto en su portafolio.

### Tests:
Buen avance! pasan la cobertura solicitada, te sugiero que también agreguen tests para la parte de posteo y para lograr ello deben separar la parte lógica del archivo `social_network.js`

### index.html:
Bien validado el `html`. Te sugerimos utilizar más etiquetas semánticas, así como sus propiedades. En el caso del label, este puede estar asociado con un control mediante la utilizacion del atributo `for`, está pendiente en esta parte:
https://github.com/Grecia2727/lim-2018-05-bc-core-am-socialnetwork/blob/c8595fa93dd09be1edb6ac79aabba068ac6a57c7/src/timeline.html#L55-L62

### style.css:
Puedes unificar los archivos style1 y style2, si lo separaste porque cada una pertenece a archivos diferentes, puedes ser más descriptiva en el nombre.

Por último te recomendamos utilizar convenciones para tus archivos, de tal forma que se mantenga un orden y se vea profesional.
Recuerda declarar tus variables, clases, id con nombres en inglés y descriptivas.

Espero puedas implementar este feedback en tus proyectos.

**Comment by Grecia2727** [comment]
Gracias Ruth, vamos a tener en cuenta tus recomendaciones.
Saludos
